[tool.pixi.feature.pyverlegacy.dependencies]
python = "~=3.11.12"

[tool.pixi.feature.testlegacy.tasks.testlegacy]
args = [{ "arg" = "glob_pat" }]
env = { PYTHONPATH = "src" }
cmd = "python -m unittest discover -s tests -p '{% raw %}{{glob_pat}}{% endraw %}' -v"
